vittorone/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

vittorone/market/urls.py
from django.urls import path
from . import views

app_name = 'market'

urlpatterns = [
    path('', views.market_index, name='index'),
    path('item/<slug:slug>/', views.item_details, name='item_details'),
    path('sell/', views.sell_view, name='sell')
]

vittorone/vittorone/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('market.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()                                                             # only for development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)                         # only for development

vittorone/accounts/models.py
from django.db import models

# Create your models here.

vittorone/market/models.py
from django.db import models

class Item(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.PositiveSmallIntegerField()
    slug = models.SlugField()
    image = models.ImageField(upload_to='item_images/%Y/%m/%d/', default='default.jpg')
    # add id system later

    def __str__(self):
        return f'{self.name} - {self.price}€'

    def snippet(self):
        if len(self.description) > 50:
            return self.description[:50] + '...'
        else:
            return self.description

vittorone/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class NameForm(forms.Form):
    username = forms.CharField(label='Your name')

vittorone/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import NameForm

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('market:index')

    elif request.method == 'GET':
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return HttpResponseRedirect(request.POST.get('next'))
            else:
                return HttpResponseRedirect(request.POST.get('next'))

    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', { 'form':form })

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('market:index')

vittorone/market/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Item
from django.contrib.auth.decorators import login_required

def market_index(request):
    items = Item.objects.all()
    return render(request, 'market/market_index.html', { 'items': items })

def item_details(request, slug):
    item = Item.objects.get(slug=slug)
    return render(request, 'market/item_details.html', { 'item': item })

@login_required(login_url='/accounts/login')
def sell_view(request):
    return render(request, 'market/sell.html')

vittorone/accounts/templates/accounts/login.html
{% extends 'layout.html' %}

{% block content %}
<h2>Log in</h2>
  <form class="login-form" action="/accounts/login/" method='post'>
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Log in">
  </form>
{% endblock %}

vittorone/accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
  <form class="signup-form" action="/accounts/signup/" method='post'>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
  </form>
{% endblock %}

vittorone/market/templates/market/item_details.html
{% extends 'layout.html' %}

{% block content %}
  <div class="item-details">
    <h1>{{ item.name }}</h1>
    <img src="{{ item.image.url }}" height="200px" width="200px">
    <p>{{ item.description }}</p>
    <h3>{{ item.price }}€</h3>
  </div>
{% endblock %}

vittorone/market/templates/market/market_index.html
{% extends 'layout.html' %}

{% block content %}
    <div class="item_list">
      {% for item in items %}
        <div class="item">
          <h2><a href="{% url 'market:item_details' slug=item.slug %}">{{ item.name }}</a></h2>
          <p>{{ item.snippet }}</p>
          <p>{{ item.price }}€</p>
        </div>
      {% endfor %}
    </div>
{% endblock %}

vittorone/market/templates/market/sell.html
{% extends 'layout.html' %}
{% block content %}
  <div class="sell">
    <h2>Sell your vittorone item</h2>
  </div>
{% endblock %}

vittorone/templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vittorone Marketplace</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <a href="{% url 'market:index'%}"><img src="{% static 'logo.jpg' %}" alt="GiovaneUomo" width="100px" height="20px"></a>
    <nav>
      <ul>
        <li>
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Log out</button>
          </form>
        </li>
      </ul>
    </nav>
    {% block content %}
    {% endblock %}

  </body>
</html>